<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="ManageUsers.aspx.cs" Inherits="Admin_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
   <link href="../Content/bootstrap.min.css" rel="stylesheet" />
    <script src="../Scripts/jquery-3.5.0.min.js"></script>
    <script src="../Scripts/popper.min.js"></script>
    <script src="../Scripts/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="../https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css"/>
    <link rel="preconnect" href="../https://fonts.gstatic.com"/>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
            <h2 style="font-size:30px;font-weight:bold;font-family:Arial, Helvetica, sans-serif;margin-bottom:35px">Manage Users</h2>
            <asp:GridView ID="GridView1" runat="server" CssClass="table table-dark table-striped"   Height="144px" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="UserID" DataSourceID="SqlDataSource1">

                <Columns>
                    <asp:BoundField DataField="UserID" HeaderText="UserID" InsertVisible="False" ReadOnly="True" SortExpression="UserID" />
                    <asp:BoundField DataField="UserEmail" HeaderText="UserEmail" SortExpression="UserEmail" />
                    <asp:BoundField DataField="UPassword" HeaderText="UPassword" SortExpression="UPassword" />
                    <asp:BoundField DataField="UserMobile" HeaderText="UserMobile" SortExpression="UserMobile" />
                    <asp:BoundField DataField="RoleID" HeaderText="RoleID" SortExpression="RoleID" />
                    <asp:BoundField DataField="FullName" HeaderText="FullName" SortExpression="FullName" />
                    <asp:BoundField DataField="SecQue" HeaderText="SecQue" SortExpression="SecQue" />
                    <asp:BoundField DataField="SecAns" HeaderText="SecAns" SortExpression="SecAns" />
                    <asp:BoundField DataField="Dated" HeaderText="Dated" SortExpression="Dated" />
                    <asp:CheckBoxField DataField="Active" HeaderText="Active" SortExpression="Active" />
                </Columns>

            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:TathaastuCon %>" SelectCommand="SELECT * FROM [Users]" UpdateCommand="UPDATE Users
SET       [UserEmail] =@UserEmail, [UPassword] =@UPassword, [UserMobile] =@UserMobile, [RoleID] =@RoleID, [FullName] =@FullName, [SecQue] =@SecQue, [SecAns] =@SecAns, [Dated] =@Dated, [Active] =Active 
           where UserID=@UserID " DeleteCommand="DELETE FROM Users WHERE UserID=@UserID ">
            </asp:SqlDataSource>
        </ContentTemplate> 
    </asp:UpdatePanel>

</asp:Content>

