<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="ManageNGOs.aspx.cs" Inherits="Admin_ManageNGOs" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
   <link href="../Content/bootstrap.min.css" rel="stylesheet" />
    <script src="../Scripts/jquery-3.5.0.min.js"></script>
    <script src="../Scripts/popper.min.js"></script>
    <script src="../Scripts/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="../https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css"/>
    <link rel="preconnect" href="../https://fonts.gstatic.com"/>
     
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
        <h2 style="font-size:30px;font-weight:bold;font-family:Arial, Helvetica, sans-serif;margin-bottom:35px">Manage NGOs</h2>
    
       
        <asp:GridView CssClass="table table-dark table-striped" ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="NGOID" DataSourceID="SqlDataSource1" Height="144px">
        <Columns>
            <asp:BoundField DataField="NGOID" HeaderText="NGOID" InsertVisible="False" ReadOnly="True" SortExpression="NGOID" />
            <asp:BoundField DataField="NGOName" HeaderText="NGOName" SortExpression="NGOName" />
            <asp:BoundField DataField="NGOAddress" HeaderText="NGOAddress" SortExpression="NGOAddress" />
            <asp:BoundField DataField="NGOEmail" HeaderText="NGOEmail" SortExpression="NGOEmail" />
            <asp:BoundField DataField="NGOMobile" HeaderText="NGOMobile" SortExpression="NGOMobile" />
            <asp:BoundField DataField="RegNo" HeaderText="RegNo" SortExpression="RegNo" />
            <asp:BoundField DataField="SectorID" HeaderText="SectorID" SortExpression="SectorID" />
            <asp:BoundField DataField="NGOTypeID" HeaderText="NGOTypeID" SortExpression="NGOTypeID" />
            <asp:BoundField DataField="StateID" HeaderText="StateID" SortExpression="StateID" />
            <asp:BoundField DataField="DistrictID" HeaderText="DistrictID" SortExpression="DistrictID" />
            <asp:BoundField DataField="NGOPassword" HeaderText="NGOPassword" SortExpression="NGOPassword" />
            <asp:BoundField DataField="NGOSecQue" HeaderText="NGOSecQue" SortExpression="NGOSecQue" />
            <asp:BoundField DataField="NGOSecAns" HeaderText="NGOSecAns" SortExpression="NGOSecAns" />
            <asp:BoundField DataField="NGODated" HeaderText="NGODated" SortExpression="NGODated" />
            <asp:CheckBoxField DataField="NGOActive" HeaderText="NGOActive" SortExpression="NGOActive" />
            <asp:BoundField DataField="RoleID" HeaderText="RoleID" SortExpression="RoleID" />
            <asp:BoundField DataField="Approve" HeaderText="Approve" SortExpression="Approve" />
        </Columns>
    </asp:GridView>
    
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:TathaastuCon %>" SelectCommand="SELECT * FROM [NGO]" UpdateCommand="UPDATE NGO
SET       [NGOName] =@NGOName, [NGOAddress] =@NGOAddress, [NGoEmail] =@NGOEmail, [NGOMobile] =@NGOMobile, [RegNo] =@RegNo, [SectorID] =@SectorID, [NGOTypeID] =@NGOTypeID, [StateID] =@StateID, [DistrictID] =@DistrictID, [NGOPassword] =@NGOPassword, [NGOSecQue] =@NGOSecQue, [NGOSecAns] =@NGOSecAns, [NGODated] =@NGODated, [NGOActive] =NGOActive, [RoleID] =@RoleID, [Approve] =@Approve
           where NGOID=@NGOID " DeleteCommand="DELETE FROM NGO WHERE NGOID=@NGOID ">
    </asp:SqlDataSource>
</asp:Content>

